### ISSUE TITLE
Sustains left hanging across keyswitches

### ISSUE THREAD

**Issue by stevefal** [jtackaberry/flexrouter#1]
When a note key is held across a keyswitch, releasing the note still sends a noteoff to the previous channel, as expected.

But when the sustain pedal is held across a keyswitch, the pedal up is not sent to the previous channel, leaving the notes of the previous keyswitch playing. The only way to silence them is to return to the previous keyswitch and send another pedal up.

Other advanced keyswitchers associate pedal up with the channel(s) of the mating pedal down channel(s) in order to prevent these hanging notes. I argue that's the best thing to do because one does not have to mentally track manage sustain state in order to prevent the hanging. Also, managing sustain like this automatically allows you to perform a pseudo-legato across keyswitches.

**Comment by jtackaberry** [comment]
Yup, makes sense.  I'll take a crack at this problem this week.

Thanks for the report!

**Comment by jtackaberry** [comment]
Provided a global configuration option to prevent CC hanging.  Will be available in the next release.

**Comment by stevefal** [comment]
Oh boy, I'll have to try these out. It might take me a while because I'm in the middle of another big project.

**Comment by jtackaberry** [comment]
No worries!

**Comment by jtackaberry** [comment]
Fixed in 2.0.0.
