### ISSUE TITLE
Divisi use case (no issue)

### ISSUE THREAD

**Issue by stevefal** [jtackaberry/flexrouter#3]
This is not an issue, just an outline of the use case that brought me to FlexRouter, as an fyi.

I am using AudioBro LASS string library which provides ~15 articulations for each of Vlns I, Vlns II, Vlas, Celli and Bass. Each section has subsections A, B, C for divisi and First Chair players. There are also a few second chair players.

LASS has an advanced divisi generator that is built into each patch as a script. There is no communication between patches, but since each patch contains the same divisi script, the players effectively coordinate because they receive the same input and execute the same logic, albeit each typically with a different role.

I don't like to use these built-in scripts for two reasons: 1) The computed parts are not recorded verbatim, which means they are not directly editable, and 2) the divisi algorithm has a programmatic delay, which results in more difficult editing wrt timing.

Instead of using the built-in scripts, I run a set of proxy LASS patches running the scripts in a standalone version of Kontakt with "send MIDI to the outside world" This results in the divisi parts generating actual MIDI events for all voice lines, and lets me record, see and edit the actual notes played.

Finally, I used TouchOSC and a table to select articulations. I use a CC31 values 1-15 for this. The data flow is as follows:

![Image of Yaktocat](https://i.imgur.com/m9Kn3Id.png)

"ARC" is the LASS keyswitcher (among other things) that I'd like to replace with FlexRouter, because FR supports CC's directly, and it supports more simultaneous keyswitches.

LASS's keyswitcher has some limitations but is sophisticated and pretty well proven with customers.

The way I'm using FlexRouter for this scenarios is to create four rules for each of Divisi A, B, C, FC and 2nd. Each rule sets up CC31 values 1-15 to map MIDI channels 2,3,4, 5 and 6 to Kontakt MIDI channels A1-A15, B1-B15, etc:

Rule Divisi A
  CC31/1: ch2 > chA1
  CC31/2: ch2 > chA2
...
Rule Divisi B
  CC31/1: ch3 > chB1
  CC31/2: ch3 > chB2
...
...

I am using multiple rules because unless I am missing something, I cannot create multiple mappings per keyswitch within one rule.
I hope this sheds light on one use case.

**Comment by jtackaberry** [comment]
Thanks for sharing!  This is indeed a pretty sophisticated use case.

I don't own LASS but I'm of course aware of the venerable ARC.  I'm quite interested to hear you're using FlexRouter in lieu of ARC for expanded flexibility.  That's very encouraging!

You're right that you'd need to create multiple rules if you want a given keyswitch to trigger routes to multiple target channels.  Another reason you'd need separate rules is if you want a given keyswitch to be triggerable from multiple source channels, as currently the keyswitch source channel is a per-rule parameter.

Thanks!

**Comment by jtackaberry** [comment]
I said:

> You're right that you'd need to create multiple rules if you want a given keyswitch to trigger routes to multiple target channels.

As of 2.0.0. this isn't quite true now.  Although it's not as fully baked as it might be, it is now possible to create multiple instances of the same keyswitch in a rule, and give them different redirects, sources, and targets.
