### ISSUE TITLE
Save/Load rule sets

### ISSUE THREAD

**Issue by stevefal** [jtackaberry/flexrouter#4]
It would be useful to be able to save and load rule sets. Complex rule sets take some time to create, and duplicating them manually is error-prone.

One can anticipate that with new versions of FR being released, users will need to recreate their rules after applying an updated script. Supporting Save/Load will ease adoption of updates since users will be able to easily try them using preexisting rule sets that they've saved.

However this feature has its own complication in that some updates may be incompatible with previous rule file formats or schemas. Therefore, a rule-file versioning system would help. Maybe separately from FR script version numbers, the rule file format could have its own version number. That way a script can check a file's format version before attempting to load it, and either accept, filter or reject the load request according to whatever compatibility constraints apply.

Ideally the rule set file format never changes so much that it breaks in future versions of the script. But this is hard to guarantee, so a simple system to trigger an appropriate behavior will be helpful down the road.

**Comment by jtackaberry** [comment]
This is where we very rapidly run into the aggravating limitations of KSP.

But won't user presets get you most of the way there?  In the Preset menu, you can click Save Preset and then call it up again later.  This is what I do.

When there is a new release of FlexRouter, you'd call up the preset, drop in the new script, and save it back out.  Unfortunately you still need to refresh the preset in all your Kontakt instances, but you would need to do this anyway to update the script.

Have I misunderstood your request?

**Comment by stevefal** [comment]
Ok, after reading about how script persisted data works, I see what you're suggesting. I think the caveat for users is that in order to preserve data (for past persisted variables), one must update the script manually by pasting code and "Apply". Loading a script from the Preset menu into the current tab will purge the persisted data that was already there:

> Please note: if you load a script from the script menu, the value of persistent variables is NOT
> buffered. This is necessary, since for example you could have more than one script with the
> same variable name.
> So if you load a script which contains the variable name $Time (say for example a delay
> script), make some changes and then load a different script which contains the same variable
> name (say for example sequencing script), you would not want the changes of the first script
> to be applied to the second script.

This is not inconsistent with the method you've outlined. I'm just understanding the significance of it relative to preserving existing rule sets.

Load/Save would be a more formal system or memorializing settings, but I can imagine that it's a non-trivial bit of work, and saving presets is a reasonable workaround.

Btw LASS ARC supports Load/Save of its configurations, but I don't know how it does it.

If FR did everything else I need, I'd be more than happy to use Presets as my way of saving rule sets.

**Comment by jtackaberry** [comment]
It's _possible_ to read and write external files, it's just cumbersome and limited.  (But that is the general theme with  KSP.)  I'd definitely like to avoid implementing that if I can. :)

You're right about updating new versions of the script: pasting the code into the script text area and clicking apply will preserve settings.  And as far as I can tell, there is no simpler way of upgrading -- it requires a painstaking, manual replacement of the multiscript in each instance.  I would love to know if there is a simpler way.

"Manual replacement" in this case is either copy/pasting the script, or pulling in a new user preset.  In the former case, existing settings are preserved, and in the latter case, they are replaced with the user preset.

So if you have a set of rules you use frequently in many instances, you'd certainly want to save it as a preset.  And then updating FlexRouter within that preset involves loading it, copy/pasting the new code in (which preserves settings), and saving it back out.  You still need to manually update each Kontakt instance that users that preset to reload the newly updated preset.

**Comment by stevefal** [comment]
Makes sense. I support closing this issue as the Preset method is workable.

**Comment by jtackaberry** [comment]
Great!
