### ISSUE TITLE
Cloned Rules' Keyswitche Changes Are Mirrored In Source Rule 

### ISSUE THREAD

**Issue by natealexander89** [jtackaberry/flexrouter#9]
Super frustrating but maybe I'm doing something wrong-- I cloned a rule and then went through and changed the "source" and "target" routing for all the keyswitches. Went back to the rule it had been cloned from and ALL those keyswitch routings had changed as well to the revisions I made on the clone! 

Flexrouter 2.2.3
Kontakt 7.3

**Comment by natealexander89** [comment]
sorry figured it out, i was editing the KSP within VEP without the instance connected and it created this behavior. Once connected it resumed correct behavior. Thanks!

**Comment by jtackaberry** [comment]
Glad you got it sorted!
